name: line_icons
description: Another icon library, based on Awesome Line Icons (by www.icons8.com) and with the help of FlutterIcon.com
version: 0.0.1
author: galonsos@gmail.com
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: LineIcons
      fonts:
        - asset: lib/assets/fonts/LineIcons.ttf
          weight: 400
